### ISSUE TITLE
建议隐藏settings的mysql配置

### ISSUE THREAD

**Issue by CabbSir** [nxtabb/Iship#2]
里面包括mysql账号密码，以及mysql服务器ip

**Comment by nxtabb** [comment]
雾草 确实




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"CabbSir"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月19日(星期二) 晚上6:53
收件人:&nbsp;"nxtabb/Iship"<Iship@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[nxtabb/Iship] 建议隐藏settings的mysql配置 (#2)





 
里面包括mysql账号密码，以及mysql服务器ip
